/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import conexion.Cliente;

/**
 *
 * @author Gabriel
 */
public class ActualizarContraseniaPanel extends javax.swing.JPanel {

        private Cliente cliente;

        public Cliente getCliente() {
                return cliente;
        }

        public void setCliente(Cliente cliente) {
                this.cliente = cliente;
        }

        /**
         * Creates new form ActualizarContraseniaPanel
         * 
         * @param cliente
         */
        public ActualizarContraseniaPanel(Cliente cliente) {
                this.cliente = cliente;
                initComponents();
                lblSubHeader.putClientProperty("FlatLaf.styleClass", "h2");
                txtUsuario.setText(this.cliente.getId());
        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                lblSubHeader = new javax.swing.JLabel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtUsuario = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtContrasenia = new javax.swing.JPasswordField();
                cboxMostrarContraseña = new javax.swing.JCheckBox();
                btnActualizarContrasenia = new javax.swing.JButton();
                jLabel1 = new javax.swing.JLabel();

                setPreferredSize(new java.awt.Dimension(730, 520));

                lblSubHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lblSubHeader.setText("Actualizar contraseña");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblSubHeader, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jPanel2Layout.setVerticalGroup(
                                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout
                                                                .createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(lblSubHeader,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                89, Short.MAX_VALUE)
                                                                .addContainerGap()));

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 0, Short.MAX_VALUE));
                jPanel3Layout.setVerticalGroup(
                                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGap(0, 100, Short.MAX_VALUE));

                jPanel4.setBackground(new java.awt.Color(255, 255, 255));

                jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(51, 51, 51));
                jLabel2.setText("Usuario:");

                txtUsuario.setEditable(false);
                txtUsuario.setBackground(new java.awt.Color(204, 204, 204));
                txtUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
                txtUsuario.setToolTipText("");
                txtUsuario.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                txtUsuarioActionPerformed(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(51, 51, 51));
                jLabel3.setText("Nueva contraseña");

                txtContrasenia.setBackground(new java.awt.Color(204, 204, 204));
                txtContrasenia.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

                cboxMostrarContraseña.setBackground(new java.awt.Color(255, 255, 255));
                cboxMostrarContraseña.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
                cboxMostrarContraseña.setForeground(new java.awt.Color(51, 51, 51));
                cboxMostrarContraseña.setText("Mostrar contraseña");
                cboxMostrarContraseña.setBorder(null);
                cboxMostrarContraseña.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cboxMostrarContraseñaActionPerformed(evt);
                        }
                });

                btnActualizarContrasenia.setBackground(new java.awt.Color(0, 0, 51));
                btnActualizarContrasenia.setFont(new java.awt.Font("Cascadia Code", 0, 18)); // NOI18N
                btnActualizarContrasenia.setForeground(new java.awt.Color(255, 255, 255));
                btnActualizarContrasenia.setText("Actualizar contraseña");
                btnActualizarContrasenia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                btnActualizarContrasenia.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnActualizarContraseniaActionPerformed(evt);
                        }
                });

                jLabel1.setText("Para cambiar la contraseña, ingresa tu nueva contraseña.");

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(16, 16, 16)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(jLabel1)
                                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                                                .addComponent(btnActualizarContrasenia,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                222,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18))
                                                                                .addGroup(jPanel4Layout
                                                                                                .createSequentialGroup()
                                                                                                .addGroup(jPanel4Layout
                                                                                                                .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(txtContrasenia,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                550,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel3)
                                                                                                                .addComponent(txtUsuario,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                550,
                                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(jLabel2)
                                                                                                                .addComponent(cboxMostrarContraseña))
                                                                                                .addContainerGap(164,
                                                                                                                Short.MAX_VALUE)))));
                jPanel4Layout.setVerticalGroup(
                                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(11, 11, 11)
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtUsuario,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                33,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txtContrasenia,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                40,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cboxMostrarContraseña)
                                                                .addGap(7, 7, 7)
                                                                .addComponent(btnActualizarContrasenia,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                50,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap(11, Short.MAX_VALUE)));

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                jPanel1Layout.setVerticalGroup(
                                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jPanel2,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel4,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jPanel3,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jPanel1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)));
        }// </editor-fold>//GEN-END:initComponents

        private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtUsuarioActionPerformed
                // TODO add your handling code here:
        }// GEN-LAST:event_txtUsuarioActionPerformed

        private void cboxMostrarContraseñaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cboxMostrarContraseñaActionPerformed
                if (cboxMostrarContraseña.isSelected()) {
                        txtContrasenia.setEchoChar((char) 0); // Mostrar el texto
                } else {
                        txtContrasenia.setEchoChar('*'); // Ocultar el texto
                }
        }// GEN-LAST:event_cboxMostrarContraseñaActionPerformed

        private void btnActualizarContraseniaActionPerformed(java.awt.event.ActionEvent evt) {
                String password = new String(txtContrasenia.getPassword());// GEN-FIRST:event_btnActualizarContraseniaActionPerformed
                if (txtContrasenia != null && !password.isBlank()) {
                        try {
                                this.getCliente().intercambiarMensajes(
                                                this.getCliente().getId() + ";;;" + password
                                                                + ",;,Usuarios,;,CambioPassword");
                        } catch (IOException ex) {
                                Logger.getLogger(GestionEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        if (this.getCliente().obtenerCodigo().equals("200")) {
                                JOptionPane.showMessageDialog(this, "Modificada con éxito");
                        } else {
                                JOptionPane.showMessageDialog(this, this.getCliente().obtenerMensaje(),
                                                "Error" + this.getCliente().obtenerCodigo(), JOptionPane.ERROR_MESSAGE);
                        }
                } else {
                        JOptionPane.showMessageDialog(this, "NO SE MODIFICO. La password no puede ser vacia.");
                }
        }// GEN-LAST:event_btnActualizarContraseniaActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnActualizarContrasenia;
        private javax.swing.JCheckBox cboxMostrarContraseña;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JLabel lblSubHeader;
        private javax.swing.JPasswordField txtContrasenia;
        private javax.swing.JTextField txtUsuario;
        // End of variables declaration//GEN-END:variables
}
