/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import java.awt.Font;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

import conexion.Cliente;
import java.awt.Color;

/**
 *
 * @author Gabriel
 */
public class AltaEvaluacionPanel extends javax.swing.JPanel {
    private String tituloEvaluacion;
    private Cliente cliente;
    private JPanel panelContent;

    /**
     * Creates new form AltaEvaluacionPanel
     */
    public AltaEvaluacionPanel(Cliente cliente, JPanel panelContent) throws FileNotFoundException {
        this.cliente = cliente;
        this.panelContent = panelContent;
        initComponents();
        jLabel2.putClientProperty("FlatLaf.styleClass", "h2");
    }

    /**
     * Este método devuelve el título de la evaluación.
     *
     * @return el título de la evaluación.
     */
    public String getTituloEvaluacion() {
        return tituloEvaluacion;
    }

    /**
     * Este método devuelve el cliente actual.
     *
     * @return el cliente actual.
     */
    public Cliente getCliente() {
        return cliente;
    }

    /**
     * Este método establece el título de la evaluación.
     *
     * @param tituloEvaluacion el título que se asignará a la evaluación.
     */
    public void setTituloEvaluacion(String tituloEvaluacion) {
        this.tituloEvaluacion = tituloEvaluacion;
    }

    /**
     * Este método establece el cliente actual.
     *
     * @param cliente el cliente que se asignará.
     */
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevaPregunta = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        txtMensaje = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbxRespuestasValidas = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        PanelVista = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 520));

        btnNuevaPregunta.setBackground(new java.awt.Color(51, 0, 204));
        btnNuevaPregunta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevaPregunta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaPregunta.setText("Nueva Pregunta");
        btnNuevaPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaPreguntaActionPerformed(evt);
            }
        });

        btnFinalizar.setBackground(new java.awt.Color(0, 0, 51));
        btnFinalizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(255, 255, 255));
        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        txtTitulo.setBackground(new java.awt.Color(204, 204, 204));
        txtTitulo.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        txtTitulo.setForeground(new java.awt.Color(102, 102, 102));
        txtTitulo.setText("Titulo de la Evaluacion");
        txtTitulo.setBorder(null);
        txtTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTituloFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTituloFocusLost(evt);
            }
        });
        txtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTituloActionPerformed(evt);
            }
        });

        txtMensaje.setFont(new java.awt.Font("Lucida Console", 2, 24)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(255, 0, 0));

        btnAtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    btnAtrasActionPerformed(evt);
                } catch (IOException e) {

                    e.printStackTrace();
                }
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Título de la evaluación");

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Crear una evaluación");

        cbxRespuestasValidas.setText("Permitir al estudiante ver las respuestas correctas");

        PanelVista.setBackground(new java.awt.Color(204, 204, 204));
        PanelVista.setOpaque(false);
        PanelVista.setLayout(new javax.swing.BoxLayout(PanelVista, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(PanelVista);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Vista previa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(57, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 84,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(367, 367, 367))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        layout.createSequentialGroup()
                                                                                .addComponent(jLabel1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        162,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(156, 156, 156)
                                                                                .addComponent(cbxRespuestasValidas)
                                                                                .addGap(28, 28, 28))
                                                                .addComponent(txtTitulo,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 626,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 626,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnAtras,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 146,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(167, 167, 167)
                                                                .addComponent(btnNuevaPregunta,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(3, 3, 3)
                                                                .addComponent(btnFinalizar,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 155,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jLabel3))
                                                .addGap(47, 47, 47)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(cbxRespuestasValidas))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 31,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnNuevaPregunta, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnAtras, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.PREFERRED_SIZE, 48,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addComponent(txtMensaje, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Método que activa placeholder de ayuda.
     * 
     * @param texto texto de ayuda.
     */
    private void TextoAyudaOn(JTextField texto) {
        Font fuente = texto.getFont();
        fuente = fuente.deriveFont(Font.ITALIC);
        texto.setFont(fuente);
        texto.setForeground(Color.DARK_GRAY);
    }

    /**
     * Método que desactiva placeholder de ayuda.
     * 
     * @param texto texto de ayuda.
     */
    private void TextoAyudaOff(JTextField texto) {
        Font fuente = texto.getFont();
        fuente = fuente.deriveFont(Font.PLAIN);
        texto.setFont(fuente);
        texto.setForeground(Color.DARK_GRAY);
    }

    /**
     * Este método permite asignar preguntas a la evaluación actual a partir del
     * botón "Agregar Pregunta", una vez el título haya sido ingresado y único.
     *
     * @param evt
     */
    private void btnNuevaPreguntaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnNuevaPreguntaActionPerformed
        if (txtTitulo.getText().isBlank() || txtTitulo.getText().equals("Titulo de la Evaluacion")) { // Si el titulo es
                                                                                                      // // vacio
            JOptionPane.showMessageDialog(this, "Ingrese un titulo para la evaluación", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                tituloEvaluacion = txtTitulo.getText();
                if (AltaPreguntaPanel.getCantidadPreguntas() == 0) { // Si aún no se agregaron preguntas
                    if (!this.existeTitulo(tituloEvaluacion)) { // Si el título es válido
                        cliente.setInstruccion(tituloEvaluacion);
                        txtTitulo.setEditable(false);
                        AltaPreguntaPanel ventanaPregunta = new AltaPreguntaPanel(PanelVista, cliente, "docente",
                                panelContent, this);
                        ventanaPregunta.setSize(730, 520);
                        ventanaPregunta.setLocation(0, 0);
                        panelContent.removeAll();
                        panelContent.add(ventanaPregunta);
                        panelContent.revalidate();
                        panelContent.repaint();
                    } else {
                        JOptionPane.showMessageDialog(this, "Título en uso", "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    AltaPreguntaPanel ventanaPregunta = new AltaPreguntaPanel(PanelVista, cliente, "docente",
                            panelContent, this);
                    ventanaPregunta.setSize(730, 520);
                    ventanaPregunta.setLocation(0, 0);
                    panelContent.removeAll();
                    panelContent.add(ventanaPregunta);
                    panelContent.revalidate();
                    panelContent.repaint();
                }
            } catch (IOException ex) {
                Logger.getLogger(AltaEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }// GEN-LAST:event_btnNuevaPreguntaActionPerformed

    private void txtTituloActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTituloActionPerformed

    }// GEN-LAST:event_txtTituloActionPerformed

    /**
     * Este método permite crear la evaluación a partir del botón "Finalizar",
     * una vez se haya ingresado el título y por lo menos seis preguntas.
     *
     * @param evt
     */
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnFinalizarActionPerformed
        if (txtTitulo.getText().isBlank() || txtTitulo.getText().equals("Titulo de la Evaluacion")) { // Si el titulo
                                                                                                      // esta vacio
            JOptionPane.showMessageDialog(this, "Ingrese un titulo para la evaluación", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } else
            try {
                if (AltaPreguntaPanel.getCantidadPreguntas() >= 3) {
                    // Obtener el estado del checkbox
                    boolean respuestasValidas = cbxRespuestasValidas.isSelected(); // Asigna true si está seleccionado,
                                                                                   // false si no lo está

                    // Concatenar la información necesaria para enviarla al cliente, incluyendo el
                    // valor de respuestasValidas
                    // Prepara el mensaje con el número de preguntas
                    String mensaje = ";;;" + respuestasValidas + ";;;" + AltaPreguntaPanel.getCantidadPreguntas()
                            + ",;,Evaluaciones,;,Alta";
                    cliente.concatenarMensaje(mensaje);
                    cliente.intercambiarMensajes(cliente.getInstruccion());

                    if (cliente.obtenerCodigo().equals("200")) {
                        JOptionPane.showMessageDialog(this, "Evaluacion creada con exito", "Mensaje",
                                JOptionPane.INFORMATION_MESSAGE);
                        AltaPreguntaPanel.setCantidadPreguntas(0);
                        GestionEvaluacionesPanel gestionEvaluacionesPanel = new GestionEvaluacionesPanel(cliente,
                                "docente", panelContent);
                        gestionEvaluacionesPanel.setSize(730, 520);
                        gestionEvaluacionesPanel.setLocation(0, 0);
                        panelContent.removeAll();
                        panelContent.add(gestionEvaluacionesPanel);
                        panelContent.revalidate();
                        panelContent.repaint();
                    } else {
                        JOptionPane.showMessageDialog(this, cliente.obtenerMensaje(), "Error" + cliente.obtenerCodigo(),
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Faltan elementos.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException ex) {
                Logger.getLogger(AltaEvaluacion.class.getName()).log(Level.SEVERE, null, ex);
            }
    }// GEN-LAST:event_btnFinalizarActionPerformed

    /**
     * Este método se ejecuta cuando el campo de texto 'txtTitulo' gana el foco.
     * Si el texto actual es "Titulo de la Evaluacion", lo borra y desactiva el
     * texto de ayuda.
     *
     * @param evt el evento que indica que el foco fue ganado por el campo de
     *            texto.
     */
    private void txtTituloFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtTituloFocusGained
        if (txtTitulo.getText().equals("Titulo de la Evaluacion")) {
            txtTitulo.setText(null);
            txtTitulo.requestFocus();
            TextoAyudaOff(txtTitulo);
        }
    }// GEN-LAST:event_txtTituloFocusGained

    /**
     * Este método se ejecuta cuando el campo de texto 'txtTitulo' pierde el
     * foco. Si el campo está en blanco, activa el texto de ayuda y establece
     * "Titulo de la Evaluacion" como texto predeterminado.
     *
     * @param evt el evento que indica que el foco fue perdido por el campo de
     *            texto
     */
    private void txtTituloFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_txtTituloFocusLost
        if (txtTitulo.getText().isBlank()) {
            TextoAyudaOn(txtTitulo);
            txtTitulo.setText("Titulo de la Evaluacion");
        }
    }// GEN-LAST:event_txtTituloFocusLost

    /**
     * Este método da funcionamiento al botón "Atrás", que devuelve a la ventana
     * de gestión.
     *
     * @param evt
     * @throws IOException
     */
    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnAtrasActionPerformed

        try {
            GestionEvaluacionesPanel gestionEvaluacionesPanel = new GestionEvaluacionesPanel(cliente, "docente",
                    panelContent);
            gestionEvaluacionesPanel.setSize(730, 520);
            gestionEvaluacionesPanel.setLocation(0, 0);
            panelContent.removeAll();
            panelContent.add(gestionEvaluacionesPanel);
            panelContent.revalidate();
            panelContent.repaint();
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }// GEN-LAST:event_btnAtrasActionPerformed

    /**
     * Este método solicita al server si el título de una evaluación a crear ya
     * existe.
     *
     * @param titulo de la evaluación.
     * @return true si existe y false en caso contrario.
     * @throws IOException
     */
    private boolean existeTitulo(String titulo) throws IOException {
        String instruccion = cliente.formatearMensaje(titulo, "Evaluaciones", "Existencia");
        cliente.intercambiarMensajes(instruccion);
        return cliente.obtenerCodigo().equals("200");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelVista;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnNuevaPregunta;
    private javax.swing.JCheckBox cbxRespuestasValidas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
