/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui;

import conexion.Cliente;

/**
 *
 * @author Gabriel
 */
public class BienvenidaPanel extends javax.swing.JPanel {

    /**
     * Creates new form BienvenidaPanel
     */
    public BienvenidaPanel(Cliente cliente, String rol) {
        initComponents();
        lblSubtitulo.putClientProperty("FlatLaf.styleClass", "h2");
        if (rol.equals("docente")) {
            txtPrimerRenglon.setText("Este es el espacio donde podrás crear y gestionar evaluaciones de manera fácil.");
            txtSegundoRenglon.setText(
                    " Aquí también podrás acceder a los historiales de evaluaciones para un seguimiento detallado. ");
        }
        if (rol.equals("estudiante")) {

            txtPrimerRenglon
                    .setText(
                            "Este es el espacio donde podrás realizar evaluaciones de manera fácil y ver sus resultados.");
            txtSegundoRenglon.setText(
                    " Aquí también podrás acceder a los historiales de evaluaciones para un seguimiento detallado. ");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSubtitulo = new javax.swing.JLabel();
        txtPrimerRenglon = new javax.swing.JLabel();
        txtSegundoRenglon = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(730, 520));
        setRequestFocusEnabled(false);

        lblSubtitulo.setText("Bienvenido ");

        txtPrimerRenglon.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtPrimerRenglon.setText("Este es el espacio donde podrás crear y gestionar evaluaciones de manera fácil.");

        txtSegundoRenglon.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtSegundoRenglon.setText(
                " Aquí también podrás acceder a los historiales de evaluaciones para un seguimiento detallado. ");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagenbienvenida.png"))); // NOI18N
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSubtitulo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtSegundoRenglon, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtPrimerRenglon, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        686, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 710,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(txtPrimerRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSegundoRenglon, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(98, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel txtPrimerRenglon;
    private javax.swing.JLabel txtSegundoRenglon;
    // End of variables declaration//GEN-END:variables
}
